### ISSUE TITLE
Questions about `DataFile#Path`

### ISSUE THREAD

**Issue by paulmillar** [SciCatProject/backend#1000]
The schema description of [DataFile#path](https://github.com/SciCatProject/scicat-backend-next/blob/master/src/common/schemas/datafile.schema.ts) path says:

> Relative path of the file within the dataset folder.

I have a few questions on this `path` property and its description.

  * Normally non-absolute (i.e., relative) paths must not start with a `/` character; e.g., `foo/bar/baz.hd5` is a relative path while `/foo/bar/baz.hd5` is an absolute path. Does that requirement apply to the `path` property?

  * If `path` property were to start with a `/`, would it be considered an absolute path or would it still be considered a relative path?

  * What is "the dataset folder" ?

    The only reference to a "folder" I found in the [`Dataset schema`](https://github.com/SciCatProject/scicat-backend-next/blob/master/src/datasets/schemas/dataset.schema.ts) was   `sourceFolder`.  Are `DataFile#path` values resolved against the (absolute) path in `Dataset#sourceFolder`?

Cheers,
Paul.

**Comment by bpedersen2** [comment]
I would say, it depends. 

Scicat itself does not access files in any way, only the (separate and facility specific) downloader  service and e.g. the sciatecean/jupyternotebook service would access files. These services should map path the in a facility-specific way.

And if you have an archive/unarchive flow as e.g. PSI where data may not be available directly, the mapping may be different as well.

**Comment by nitrosx** [comment]
SciCat does not impose any constraint on `datafile:path`. It all depends how you use your metadata downstream and any validation is responsibility of the data curator.

You have two main use cases:
 - use both `dataset:sourceFolder` and `datafile:path`. The full path of the file is the path obtained by joining the content of the two fields. It is assumed that `datafile:path` is a relative path.
 - use only `datafile:path`. In this case the field can contain an absolute or relative path depending on your IT infrastructure, how you provide access to the files and how the services consuming the info are setup

**Comment by paulmillar** [comment]
Hi guys,

Thanks for the very quick response.

I suggest the documentation is updated to make this clearer. 

If you like, I can have a go and create a corresponding pull-request.

**Comment by nitrosx** [comment]
You are more than welcome!!!
...and we will welcome your PR updating the documentation. 
Thank you so much

**Comment by sbliven** [comment]
As a concrete example, at PSI we expect `OrigDataBlock` files to be a path on the archiver server relative to the data root. They don't have leading slash and are usually of the form `{nfs mount}/{creationLocation}/{filename}`. The `DataBlock` files have the same path, but in this case they refer to files within a tarball on our tape system (stored in the `archiveId` field).

I recently added some info about the two types of DataBlock [here](https://scicatproject.github.io/documentation/Development/v4.x/Data_Model.html#origdatablocks-and-datablocks) recently. Maybe that helps? Thanks for your feedback!

**Comment by nitrosx** [comment]
@paulmillar do you have more questions regarding this issue or can I close it?

**Comment by paulmillar** [comment]
Yes, I think we can close this issue.

I've opened a fresh issue (see #1164) to update the schema with the information obtained from this issue.  I hope to submit a pull request "soon" that would closes #1164, but I can't seem to assign that issue to myself :-/

**Comment by nitrosx** [comment]
@paulmillar #1164 has been assigned to you.
thank you so much for taking care of that.

Closing this issue.
