### ISSUE TITLE
HistoryClass updatedAt

### ISSUE THREAD

**Issue by ChuckMoe** [SciCatProject/backend#1055]
### Summary
The OpenAPI definition of HistoryClass's `updatedAt` differs from the implementation.
The Javascript Date object is being represented in milliseconds. The OpenAPI Date is being represented as a DateTime String.
Which is supposed to be used for the API call?

https://github.com/SciCatProject/scicat-backend-next/blob/0cc05295bb06282aefdbbb0230c217b37efa81b3/src/datasets/schemas/history.schema.ts#L43-L54

**Comment by nitrosx** [comment]
Thank you for reporting this.
updateAt fields should be consistent through out all the schemas.
I am going to check what do we have in the other schema and get back to you

**Comment by nitrosx** [comment]
Please check the queryable schema which include the same field:
```
  @ApiProperty({
    type: Date,
    description:
      "Date and time when this record was updated last. This property is added and maintained by mongoose.",
  })
  @Prop({
    type: Date,
  })
  updatedAt: Date;
```

I would do the same

**Comment by nitrosx** [comment]
I actually think that the best solution is to have the history schema inheriting from queryable schema. 
That would solve the current issue

**Comment by nitrosx** [comment]
Scratch my suggestion in the previous post.
I just checked the fields createdAt and updatedAt are in the [ISO 8601](https://en.wikipedia.org/wiki/ISO_8601) format.
In my dataset, they look like the following:
```
  "createdAt": "2024-02-27T12:26:57.313Z",
  "updatedAt": "2024-02-27T12:26:57.313Z",
```
HistoryClass updatedAt should be the same.

**Comment by nitrosx** [comment]
I finally figure out it works.
The _updatedAt_ and _createdAt_ fields are managed via Mongoose and the time stamp feature.
In every schema definition, the @Schema decorator can contain the timestamp parameter which controls which fields are updated automatically with the timestamps.
Like is explained in [Mongoose docs](https://mongoosejs.com/docs/timestamps.html), setting `timestamps: true` will force Mongoose to add createdAt/updatedAt field at creation time and updated updatedAt anytime the document is updated.
You can decide to have only one field or the other with the correct syntax.

In case of the HistoryClass, Mongoose will add and update the filed _updatedAt_ automatically with timestamp in ISO 8601 format.

I am putting a PR in to update the documentation.

**Comment by nitrosx** [comment]
No change required, except swagger documentation update. PR submitted

**Comment by ChuckMoe** [comment]
This PR does not really solve this issue @nitrosx. The issue is the difference between the example (int) and the real value (date-time string). OpenAPI compares both and notices that there is a difference, which is correct.

`default: Date.now()` returns an int value but setting `type: Date`makes it expect a date-time string. To solve the problem this PR was opened for, simply replace `default: Date.now()` with a harcoded example.

https://github.com/SciCatProject/scicat-backend-next/blob/23e4476b80555c91a2fc47642400d2374d97ed39/src/datasets/schemas/history.schema.ts#L43-L55
