### ISSUE TITLE
undefined in published data? 

### ISSUE THREAD

**Issue by rkweehinzmann** [SciCatProject/backend#1090]
on release-jobs branch 
(pysc) root@vmforsctests:/scratch/work/scicat-backend-next# npm start

> scicat-backend-next@4.0.0 start
> nest start

src/published-data/published-data.service.ts:74:31 - error TS2345: Argument of type 'QueryOptions<unknown> | undefined' is not assignable to parameter of type '(CountOptions & Omit<MongooseQueryOptions<PublishedDataDocument>, "timestamps" | "lean">) | null | undefined'.
  Type 'QueryOptions<unknown>' is not assignable to type 'CountOptions & Omit<MongooseQueryOptions<PublishedDataDocument>, "timestamps" | "lean">'.
    Type 'QueryOptions<unknown>' is not assignable to type 'CountOptions'.
      Types of property 'session' are incompatible.
        Type 'ClientSession | null | undefined' is not assignable to type 'ClientSession | undefined'.
          Type 'null' is not assignable to type 'ClientSession | undefined'.

74       .countDocuments(filter, options)
                                 ~~~~~~~

Found 1 error(s).

**Comment by nitrosx** [comment]
Code in src/published-data/published-data.service.ts of this _release-jobs_ branch different from master.
I backported the change in to the _release_jobs_.
Waiting to hear if that solves the problem

**Comment by rkweehinzmann** [comment]
It solved the problem, thanks !

**Comment by rkweehinzmann** [comment]
It solved the problem, thanks! closing then.
