### ISSUE TITLE
Implement MVP actions

### ISSUE THREAD

**Issue by sbliven** [SciCatProject/backend#1123]
Demonstrate (manually) a minimum-viable-produce job flow.

1. Create a new 'archive' job after a dataset is marked for archiving
2. Execute a URLAction calling a URL with the jobid
3. In response to the HTTP call, the mock archiver responds by updating the status to `jobSuccessful`

This might make use of the [ScicatArchiveMock](https://github.com/SwissOpenEM/ScicatArchiveMock) created by @consolethinks.

Ideally this would be converted into an integration test, but for now a manual test would suffice.

**Comment by despadam** [comment]
Confirmed by @phwissman that the MVP is fully functional. 

TODO:
- Tests are still missing and will be covered by: https://github.com/SciCatProject/scicat-backend-next/issues/1435
- allow for multiple storage location, as seen here: https://github.com/SciCatProject/scicat-backend-next/issues/1124 as Filters
