### ISSUE TITLE
EmailJobAction should accept the email body from a file

### ISSUE THREAD

**Issue by sbliven** [SciCatProject/backend#1152]
The body of the email was typically a fairly long handlebars template. See [job-template.html](https://github.com/SciCatProject/scicat-backend-next/blob/master/src/common/email-templates/job-template.html).

`EmailJobAction` should have a configuration option to specify this as a filename rather than directly in the config file. It should default to `common/email-templates/job-template.html`.

**Comment by despadam** [comment]
Done in https://github.com/SciCatProject/scicat-backend-next/pull/1326
