### ISSUE TITLE
Bug in instrument authorizations

### ISSUE THREAD

**Issue by fpotier** [SciCatProject/backend#1172]
https://github.com/SciCatProject/scicat-backend-next/blob/3b4757c0c8800ac9095b187993c7aedb090d7f7a/src/casl/casl-ability.factory.ts#L1300-L1336

A user who is in both `DELETE_GROUPS` and  `ADMIN_GROUPS` will only have authorization to delete `Instruments` because of the `else if`.

**Comment by nitrosx** [comment]
@fpotier Thank you so much for reporting the bug.
We will work on it asap.

**Comment by nitrosx** [comment]
Resolved by PR #1181
