### ISSUE TITLE
No schemaless field in proposal class

### ISSUE THREAD

**Issue by rkweehinzmann** [SciCatProject/backend#1178]
## No schemaless field in proposal class
Metadata field equivalent to scientific metadata in datasets are missing in proposal class. This would be useful to have enabling DESY to take into account facility specifications (e.g. from our proposal system) concerning naming/labeling.

**Comment by bpedersen2** [comment]
Yes, that would definitly be nice to have

**Comment by nitrosx** [comment]
I agree. Any volunteer?

**Comment by nitrosx** [comment]
First of all what should we call this field:
- metadata
- custom metadata
- proposal metadata

I would go with `metadata`. any other suggestion?

**Comment by rkweehinzmann** [comment]
`metadata` should be fine (although some people may say what is NOT metadata in a metadata catalogue.. - but I wouldn't give any weight to such thinking). When we read about it, it will be clear the metadata belongs to the proposal class.

**Comment by bpedersen2** [comment]
Yes, `metadata`  is fine. 

Implementation plan: 
1)  add field as optiona to DTOs and schema
  -> this is backwards comaptible and non-intrusive, so should be easy to merge
2) implement FE rendering if desired
