### ISSUE TITLE
datasets/fullquery behaves differently with or without Elasticsearch

### ISSUE THREAD

**Issue by jl-wynen** [SciCatProject/backend#1183]
## Differences between instances with and without Elasitcsearch

There are some differences when querying between SciCat instances that run Elasticsearch vs those that don't run it. I tested with `staging.scicat.ess.eu`, `scicat.ess.eu`, and a locally deployed instance (latest GH package) w/o Elasticsearch.

### Different behaviour

When querying ESS staging for datasets, it ignores some fields in the query. E.g.
```python
import json
import httpx

response = httpx.get(
        "https://staging.scicat.ess.eu/api/v3/datasets/fullquery",
        params={
            "fields": json.dumps(
                {
                    "proposalId": "123"
                }
            ),
        },
    )
datasets = response.json()
print(len(datasets))
print(datasets[0]['proposalId'])
```
prints
```
100
67JH32
```
In fact, it does not respect `proposalId` but returns all datasets.

But when running the same query against `https://scicat.ess.eu`, I get 0 results as this proposal does not exist.

It even ignores unknown fields:
```python
import json
import httpx

response = httpx.get(
        "https://staging.scicat.ess.eu/api/v3/datasets/fullquery",
        params={
            "fields": json.dumps(
                {
                    "asd": ["ess"]
                }
            ),
        },
    )
print(response)
print(len(response.json()))
```
prints
```
<Response [200 OK]>
100
```

### Different syntax

```python
import json
import httpx

response = httpx.get(
        "https://staging.scicat.ess.eu/api/v3/datasets/fullquery",
        params={
            "fields": json.dumps(
                {
                    "ownerGroup": "ess"
                }
            ),
        },
    )
print(response)
```
prints
```
<Response [400 Bad Request]>
```
but on production, I get `<Response [200 OK]>` and a correct list of datasets.

To fix this, I need to change it to 
```python
"fields": json.dumps(
    {
        "ownerGroup": ["ess"]
    }
),
```
on staging.

**Comment by nitrosx** [comment]
They should behave exactly the same with or without ES

**Comment by Junjiequan** [comment]
This issue should be fixd by #1228 and #1184.
