### ISSUE TITLE
Create SDK repository

### ISSUE THREAD

**Issue by nitrosx** [SciCatProject/backend#1251]
### Summary
At each new release of SciCat BE, we want to auto generate all the supported SDKs in a separate repositories.
The objective is to always have the SDK (bindings, libraries) up to date to the most recent and stable version of SciCat

### Expected Behaviour
Create a new repository in SciCat project named SDK, also known as bindings or libraries.

**Comment by dylanmcreynolds** [comment]
Does this mean you want one repo with python, javascript, rust, etc?

**Comment by dylanmcreynolds** [comment]
Related to https://github.com/SciCatProject/pyscicat/issues/59

**Comment by dylanmcreynolds** [comment]
I think that pyscicat is the natural place for the python version.

**Comment by Ingvord** [comment]
We will need to store source code for compiled languages some where. Having source code for these is very much appreciated by the developers. 

Also for these having independent repo would be more preferred, as every language has its own eco system which is easier to maintain independently

**Comment by nitrosx** [comment]
Not needed for now.
SDK are generated and stored as artifacts at every merge to Master. They are also published to NPM.js and PYPI at every release.
