### ISSUE TITLE
Finalize Jobs: Store the config in each job, fix Get filtering

### ISSUE THREAD

**Issue by despadam** [SciCatProject/backend#1265]
Based on the meeting with @nitrosx and @sofyalaski on Jun 12, regarding storing the full configuration in each job vs only the configuration version, plus a few additional topics:

 Should we save the full config or only config version in a job?
--> Keep the full config in the schema instead of only version. In case of problems we re-address it. One solution could be to create a collection of configurations.

 Decide on `configVersion` format. Current (complicated) example is "configVersion": "v1.0 2024-03-01 6f3f38"
--> Should not be stored in the job schema, but the 1st line of the config file. It should be a string. Provide indicative example of what this string could look like in the documentation, but the format is in the end up to the instance admin to decide.

 On Job Update, should we check for matching configs of job vs running instance?
--> We don't need to check if they match, we use directly the config saved in the job.

 In the config file we use 'update' instead of 'statusUpdate'
--> Change it to 'statusUpdate', to be consistent 

 Should `isFilterValid` for checking the syntax of the job GET filters be expanded? If yes how?
--> For now is ok. Add a check for the user: if admin then can get all jobs, if not admin then get jobs based on ownership
--> Double check this, also for datasets

**Comment by sofyalaski** [comment]
in the `job.schema.ts` we specify a property `jobParams` which is not required. In fact when we create a `jobInstance` in the `instanceAuthoriuzationJobCreate` we never specify it. Should we? isn't keeping track of the job parameters even more important if we decided to store the full configuration?

--> Max says they do need to be saved too

**Comment by despadam** [comment]
Done in PR https://github.com/SciCatProject/scicat-backend-next/pull/1273
