### ISSUE TITLE
Bump chai-http from 4.4.0 to 5.0.0

### ISSUE THREAD

**Issue by Junjiequan** [SciCatProject/backend#1290]
## Issue Name

chai-http upgrade from 4.4.0 to 5.0.0 test fails. Closed PR #1248.
Failed test in https://github.com/SciCatProject/scicat-backend-next/pull/1248/checks

**needs manual code changes ( require vs. import in pretest.js)**

**Comment by bpedersen2** [comment]
We are now at 5.1.1 for chai-http.
