### ISSUE TITLE
Can not build latest master

### ISSUE THREAD

**Issue by Ingvord** [SciCatProject/backend#1338]
Hi, I have update my BE master branch today and found out I can not build it anymore:

```console
ingvord@<>:~/Projects/scicat/scicat-backend-next$ npm run start

> scicat-backend-next@4.0.0 start
> nest start

src/datasets/datasets.service.ts:295:5 - error TS2740: Type 'ModifyResult<Document<unknown, {}, DatasetDocument> & DatasetClass & Document<any, any, any> & { _id: ObjectId; }>' is missing the following properties from type 'DatasetClass': pid, _id, owner, contactEmail, and 17 more.

295     return await this.datasetModel.findOneAndDelete({ pid: id });
        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
src/users/users.service.ts:257:5 - error TS2740: Type 'ModifyResult<Document<unknown, {}, UserIdentityDocument> & UserIdentity & Document<any, any, any> & { _id: ObjectId; }>' is missing the following properties from type 'UserIdentity': authStrategy, created, credentials, externalId, and 4 more.

257     return removedUserIdentity;
        ~~~~~~~~~~~~~~~~~~~~~~~~~~~

Found 2 error(s).

```

Is it a real issue, or am I missing anything?

Thanks

**Comment by Junjiequan** [comment]
Could you try to delete the node_modules folder and then re-install the packages with `npm install`

**Comment by Ingvord** [comment]
Yes, it is the same

**Comment by bpedersen2** [comment]
No problems building here (master @ d42f8c487c00879f3a70d71d082f44fd490c502e) .

**Comment by Ingvord** [comment]
I did a fresh setup and indeed it now builds. However takes a few seconds (15!) to fire up the BE:

![Peek 2024-07-30 20-04](https://github.com/user-attachments/assets/0dad75aa-2fba-4a3f-9598-0f6bcdeb9022)

I have a feeling (sorry no recordings) it was much faster... is it only me? Or is it a regression?

**Comment by Ingvord** [comment]
I guess we can close this
