### ISSUE TITLE
Dataset PATCH request resets properties of datasetlifecycle to default

### ISSUE THREAD

**Issue by phwissmann** [SciCatProject/backend#1374]
### Summary
Description of the issue

### Steps to Reproduce
Describe how to reproduce the issue
1. Create a dataset
2. Patch the datasetlifecycle 
```
curl -X 'PATCH' \
  'http://scicat \
  -H 'accept: application/json' \
  -H 'Authorization: Bearer <token>' \
  -H 'Content-Type: application/json' \
  -d '{
  "datasetlifecycle": {
"archivable" : true,
"retrievable": true
}
}'
```
3. Patch the datasetlifecycle with a single property
 ```
curl -X 'PATCH' \
  'http://scicat \
  -H 'accept: application/json' \
  -H 'Authorization: Bearer <token>' \
  -H 'Content-Type: application/json' \
  -d '{
  "datasetlifecycle": {
"archivable" : true,
}
}'
```

4. Validate that the datasetlifecycle has been reset to default values for the net patched values in 3. 
`retrievable` will be reset to the `false`, the default value, even though only `archivable` should be updated.

### Current Behaviour
See previous. Seems to be a known issue 
https://github.com/SciCatProject/scicat-backend-next/blob/release-jobs/src/datasets/datasets.service.ts#L273

There is also a solution proposal in the linked stackoverflow post 
https://stackoverflow.com/questions/57324321/mongoose-overwriting-data-in-mongodb-with-default-values-in-subdocuments

### Expected Behaviour
Datasetlifecyle is patched with the values provided and any other values are not changed.

### Details
This issue requires some workaround when trying to update lifecycles in the job systems. There probably is a workaround in the PSI archiver for this issue.

**Comment by sbliven** [comment]
This is the expected behavior. PATCH with a application/json body operates only on top-level attributes. See #954 for the agreed solution (which still needs to be implemented)
