### ISSUE TITLE
Frontend development to enable table for user configuration of Facets and columns.

### ISSUE THREAD

**Issue by markbasham** [SciCatProject/backend#605]
## Issue Name
Frontend development to enable table for user configuration of Facets and columns.

### Summary
There needs to be a modal dialog which can be shown to allow the user to specify what columns to display, as well as which facets to filter on, as well as defining the order of the columns and types of the data, this needs to be the best guess where the scientific metadata is concerned.

The initial contents should be taken from a number of data entries, and this should be displayed as a treetable.

This dialogue will be accessed from different locations, so there is the requirement to hide checkmark columns at runtime dependant on where it is accessed from.

**Comment by nitrosx** [comment]
Transferred to frontend repo as issue [#1132](/SciCatProject/frontend/issues/1132)
