### ISSUE TITLE
Frontend development to enable table for user configuration of Facets and columns to be displayed when needed.

### ISSUE THREAD

**Issue by markbasham** [SciCatProject/backend#606]
## Issue Name
Frontend development to enable table for user configuration of Facets and columns to be displayed when needed.

### Summary
The user configuration table dialogue should be accessed from at least 3 locations, 

1. configure columns on the main data table (This should only show the active columns and column order items
2. configure the available filters in the filter section (This should only show the active filters section)
3. in the user configuration settings, which should include all the sections

**Comment by markbasham** [comment]
![20230719_161143](https://github.com/SciCatProject/scicat-backend-next/assets/822780/165c4918-9f4b-4b9a-b55a-729a6e82d0e5)

**Comment by nitrosx** [comment]
Transferred to Frontend issue [#1133](/SciCatProject/frontend/issues/1133)
