### ISSUE TITLE
When Scicat is started, do not show anything in the main list section of the UI until a search is run

### ISSUE THREAD

**Issue by markbasham** [SciCatProject/backend#607]
## Issue Name
When Scicat is started, do not show anything in the main list section of the UI until a search is run

### Summary
Rather than starting with showing the most recent files, scicat should start with a blank table, with some text highlighting that the user will see results once they filter or search.

**Comment by nitrosx** [comment]
Transferred to frontend issue [#1149](/SciCatProject/frontend/issues/1149)
