### ISSUE TITLE
Add a "Search" or "Apply" button to the text entry field

### ISSUE THREAD

**Issue by markbasham** [SciCatProject/backend#608]
## Issue Name
Add a "Search" or "Apply" button to the text entry field

### Summary
This is so that the search and filter is only applied to the main dataset list when this is pressed, or the enter key is pressed on the open search text.
 
### Extra Details

Here you should include details about the system (if it is unique) and possible information about a fix (feel free to link to code where relevant). Screenshots/GIFs are also fine here.

**Comment by markbasham** [comment]
![20230719_161143](https://github.com/SciCatProject/scicat-backend-next/assets/822780/12b53aa5-f0a6-4f89-aad1-dfe52a03fb60)

**Comment by nitrosx** [comment]
Transferred to frontend issue [#1148](/SciCatProject/frontend/issues/1148)
