### ISSUE TITLE
Move the 'free text' search up to a more prominent part of the main scicat page

### ISSUE THREAD

**Issue by markbasham** [SciCatProject/backend#609]
## Issue Name
Move the 'free text' search up to a more prominent part of the main scicat page

### Summary
This is so that the box can be wider to allow more information to be displayed and entered, and so that the search is highlighted as a larger part of the process.

**Comment by markbasham** [comment]
![20230719_161143](https://github.com/SciCatProject/scicat-backend-next/assets/822780/0f32d877-fe9a-4378-bb95-742439e5c948)

**Comment by nitrosx** [comment]
Transferred to frontend issue [#1147](/SciCatProject/frontend/issues/1147)
