### ISSUE TITLE
Add The columns to the main dataset list as specified by the configuration.

### ISSUE THREAD

**Issue by markbasham** [SciCatProject/backend#610]
## Issue Name
Add The columns to the main dataset list as specified by the configuration.

### Summary
This is just to link the configuration with the table column details.

### Extra Details

Here you should include details about the system (if it is unique) and possible information about a fix (feel free to link to code where relevant). Screenshots/GIFs are also fine here.

**Comment by nitrosx** [comment]
Transferred to frontend issue [#1146](/SciCatProject/frontend/issues/1146)
