### ISSUE TITLE
Update the metadata filter widgit to allow better matching options

### ISSUE THREAD

**Issue by markbasham** [SciCatProject/backend#613]
## Issue Name
Update the metadata filter widgit to allow better matching options

### Summary
to make use of the type as specified in the configuration, if this is a number or date, then the greater than / less than, between values, or equal to.

If a string, then this should be a filter or multi choice option.

**Comment by nitrosx** [comment]
Transferred to frontend issue [#1141](/SciCatProject/frontend/issues/1141)
