### ISSUE TITLE
Save Configuration options back to the backend when the save button in pressed.

### ISSUE THREAD

**Issue by markbasham** [SciCatProject/backend#616]
## Issue Name
Save Configuration options back to the backend when the save button in pressed.

### Summary
The user settings should be saved using the backend calls.

**Comment by nitrosx** [comment]
This requires to expand the userSettings endpoint.
We need to review the code to be able to be more specific.

**Comment by Ingvord** [comment]
I was reflecting on this a bit... and came up with an idea, that we should not store filters and columns user settings in the BE.

My reasoning is as follows: BE provides some common business logic i.e. it does know nothing about the FE. Also filters and columns configuration is very specific to the FE.

Should we introduce a new microservice specific for the task of storing FE specific user settings?

**Comment by nitrosx** [comment]
I'm not oppose to a new microservice to store the FE settings, but that is a decision that involves a longer discussion with the core collaborators.
IMHO, I think that we should proceed as we have planned (aka store such user settings under the BE user profile), while we start the discussion about the microservice. Once the feature has been implemented and released, we should leverage it to guide the discussion regarding the microservice.
