### ISSUE TITLE
Jobs migration: DTO

### ISSUE THREAD

**Issue by nitrosx** [SciCatProject/backend#622]
### Summary
Refactor Jobs **DTO** including decorators for swagger.

Please refer to the image below with the whiteboard info discussed during the in-person meeting and, also, the [jobs authorization documentation](https://scicatproject.github.io/documentation/Development/v4.x/backend/authorization/authorization_jobs.html)

![jobs_endpoints](https://github.com/SciCatProject/scicat-backend-next/assets/2193724/2195ff24-1392-4561-9fee-f5c23f40b944)

**Comment by ddijken** [comment]
Create
StatusUpdate

**Comment by nitrosx** [comment]
According to what we discussed in the in-person meeting, we should have a jobCreateDto and a jobStatusUpdateDto (which is different than a jobUpdateDto).

The statusUpdate DTO should contain only the fields listed in the following examples:
```
{
 “job_id” : “7289ee0e-4739-11ee-bcae-0b150b8afb9e”,
 "status" : "IN_PROGRESS",
 "message" : "Job 7289ee0e-4739-11ee-bcae-0b150b8afb9e has been started and is in progress. 10% completed.",
 "token" : "<JWT_TOKEN_FOR_ARCHIVER_SERVICE>"
}
```

**Comment by sbliven** [comment]
I think this is done. Thanks!
