### ISSUE TITLE
swagger endpoint in readme

### ISSUE THREAD

**Issue by belfhi** [SciCatProject/backend#685]
## Issue Name
swagger endpoint wrong in REAME

### Steps to Reproduce
start the dev environment as described in the README, and the API explorer is available at `http://localhost:3000/explorer` and not in `explorer-next` as it says in the README

### Expected Behaviour
README should be correct.

**Comment by nitrosx** [comment]
@belfhi thank you for reporting this issue.
I see that you already submitted a PR (#687). I'm going to check it and merge it as soon as possible.

**Comment by nitrosx** [comment]
Solved by PR #687
