### ISSUE TITLE
Request for a dummy getting started guide for a Windows 10 PC

### ISSUE THREAD

**Issue by keale** [SciCatProject/backend#779]
## Issue Name
Request for a dummy guide how to install backend on a Windows 10 PC

### Summary
I would like to set up a test SciCat instance on my development PC (Windows 10 Pro). The current readme is not sufficient in my opinion. The linked documentation refers to the old backend.
I have created the .env file as supposed and set URI to
`MONGODB_URI="mongodb://localhost:27017/dacat"`
In this way no connection to Mongodb was possible. It works with: 
`MONGODB_URI="mongodb://127.0.0.1:27017/dacat" `

It would be nice to have an example to avoid such small errors that take a lot of time.
Then it would be good to know what user's background knowledge is expected? Are experiences with Node.js, MongoDB, NestJS ... necessary? 
Does a forum or mailing list exist where a beginner could get help for SciCat?

Thanks a lot,
AlexK

**Comment by bpedersen2** [comment]
Installing on native windows will probably never be  a supported option. 

Best bet  would  be running in docker (with docker-compose) on WSL2 (windows subsystem for linux), but even this will require basic OS management knowledge.

And sa to the required knowledge, that  depends a lot on what you want to do.  If you want to extend the BE, then knowledge of MongoDB and NestJs is needed.

There are plans to revive scicatlive and upgrade it to scicat-be-next.

**Comment by bpedersen2** [comment]
Pullrequest for scicatlive: https://github.com/SciCatProject/scicatlive/pull/19

**Comment by keale** [comment]
Dear Bjorn, thank You for comment. At the I managed to get FE and BE runing at windows native, without containers. From backwards view, it is not hard. I have tried to do in native way, because the scialive alternative didn't work smooth well. I got FE in browser, but somehow it didn't find not the BE. SciAlive seems not to be active maintained, my issue from last year is still without reaction. 

Generally it is a big interest from Helmholtz Gemeinschaft for SciCat.  For me is the keypoint for an open-source project, how it looks with community? Do You have a mattermost, slack, or email list for questions?

**Comment by nitrosx** [comment]
Dear AlexK

The community is growing and is dedicated to maintain SciCat. Unfortunately, all of us have many other responsibilities and, as a consequence, at times, the response time is not what we would like to be.
We are working to structure and organize the project better, including addressing the issues that you have pointed out. We are actively looking for more volunteers to help the project.
There are channels to communicate with contributors, but, up to now, they have not been publicized and have been by-invitation only as the project was small enough. That is changing and the core collaborators are deciding what is the best way to move forward.

If you are interested in helping out, this is an open source project and I would love for you to open issues and create PR as you sit fit. I would encourage you to do so with documenting on how to run SciCat on windows.

If you would like to contribute even more, please send me a private message, and we take it from there.

**Comment by bpedersen2** [comment]
> Generally it is a big interest from Helmholtz Gemeinschaft for SciCat. For me is the keypoint for an open-source project, how it looks with community? Do You have a mattermost, slack, or email list for questions?

Helmholtz institutes ( FZ Jülich  and DESY) are actively participating in the SciCat development through DAPHNE4NFDI ( which I am also a part of) and starting to use it in large-scale production.

**Comment by keale** [comment]
Dear Max, Yes I can provide a how to for windows.

**Comment by nitrosx** [comment]
@keale thank you so much
