### ISSUE TITLE
500 internal server error for GET Method  fullfacet?facets=(keywords or techniques)

### ISSUE THREAD

**Issue by AnastasiiaDeveloper** [SciCatProject/backend#781]
When I am trying to add keywords or techniques from the existing list in the dataset creation form it shows:
 Request URL:
/api/v3/datasets/fullfacet?facets=keywords
/api/v3/datasets/fullfacet?facets=techniques
Request Method:
GET
Status Code:
500 Internal Server Error

**Comment by nitrosx** [comment]
@AnastasiiaDeveloper could you provide a screenshot of the form please and the details of the calls that the frontend (FE) makes to the backend (BE)?

**Comment by bpedersen2** [comment]
Usage error: The endpoint expects a list.  
correct url to use:
`fullfacet?facets=%5B%22keywords%22%5D&fields=%7B%7D`

which is the url-encoded form of
`fullfacet?facets=["keywords"]&fields={}`


@nitrosx 
backend logs for wrong URL:
```
2023-10-09T12:00:25.485963231+02:00 [Nest] 1  - 10/09/2023, 10:00:25 AM   ERROR [ExceptionsHandler] Unexpected token k in JSON at position 0
2023-10-09T12:00:25.485990415+02:00 SyntaxError: Unexpected token k in JSON at position 0
2023-10-09T12:00:25.485997900+02:00     at JSON.parse (<anonymous>)
2023-10-09T12:00:25.486002497+02:00     at DatasetsController.fullfacet (/home/node/app/dist/src/datasets/datasets.controller.js:322:26)
2023-10-09T12:00:25.486011038+02:00     at /home/node/app/node_modules/@nestjs/core/router/router-execution-context.js:38:29
```

**Comment by AnastasiiaDeveloper** [comment]
@nitrosx  
Yeah, sure 

@bpedersen2 
I made some changes (fullfacet?facets[]=techniques&fields=%7B%7D) according to your recommendations but it still doesn't work
It still gives "Internal server error" from Preview
![500 error](https://github.com/SciCatProject/scicat-backend-next/assets/54503859/6e2d509e-e3ca-4616-84d8-71080da7e3d1)

**Comment by bpedersen2** [comment]
> (fullfacet?facets[]=techniques

this really needs to be `facets=%5B%22keywords%22%5D`

**Comment by bpedersen2** [comment]
facets expects json (urlencoded) of the form 
```
[ "facet1", "facet2"] 
```

not some html- form values!

**Comment by AnastasiiaDeveloper** [comment]
@bpedersen2 
Alright, I got you and I did it.

Could you please send me the current documentation that describes how I should work with the techniques and keywords. 
How they can be deleted/added/edited?

Also how I should associate techniques and keywords with a dataset?

**Comment by AnastasiiaDeveloper** [comment]
@bpedersen2 
The documentation that was provided to me does not sufficiently describe how to work with keywords and techniques. That's why I'm asking about the latest  documentation, which may already have information on how to add/remove/edit keywords and techniques, as well as how to associate them with the dataset.

Since I don't have this information I have to guess how it should work and just waste my time doing it.
![datasets fullfacets](https://github.com/SciCatProject/scicat-backend-next/assets/54503859/63377c9e-2041-46b6-887f-f0214bb0ce97)
![techniques](https://github.com/SciCatProject/scicat-backend-next/assets/54503859/bc295e40-cf74-4a6a-8f03-42801283fadf)
![keywords](https://github.com/SciCatProject/scicat-backend-next/assets/54503859/042ff4e1-11fd-4c7a-adb9-eb8a6d346f6a)

**Comment by bpedersen2** [comment]
This works  the same way as for all other dataset-updates:
Issue a PATCH to api/v3/Datasets/<datasetid>
with a json payload containing the updated keyword list:
```
{ keywords: ["keyword1","keyword2"] }
```

or the same for techniques. Note that techniques should be a list of arrays: 
```
{techniques: [ {"pid": <id from panet>, "name":"<name from pannet>}, {...}...]
```
[1] https://expands-eu.github.io/ExPaNDS-experimental-techniques-ontology/ontology.json

or as more human-browsable form
[2] https://expands-eu.github.io/ExPaNDS-experimental-techniques-ontology/index-en.html#http://purl.org/pan-science/PaNET/PaNET01022

**Comment by bpedersen2** [comment]
You can always check the rest api docs at
http(s)://<your scicat-instance>/explorer

Update keywords can also be achieved by `/api/v3/datasets/{pid}/appendToArrayField`
