### ISSUE TITLE
ingestor does not have read access to proposal metadata

### ISSUE THREAD

**Issue by jkotan** [SciCatProject/backend#819]
In the old backend we ingest Dataset metadata with the ingestor account. Before it we read proposal metadata to get proposal ownerGroup and accessGroups  and set them to Dataset groups (also with the ingestor account). Unfortunately, with the new backend  the ingestor does not have any access  to the proposal Metadata even if we add ingestor to ADMIN_GROUPS.   

One get  `{"statusCode":403,"message":"Unauthorized access","error":"Forbidden"}`.

A similar error I can see on the frontend webpage when I login as ingestor and try to view any proposal metadata.

Therefore I would like to ask is this behaviour is expected and if there is any configuration variable to switch the old access right back?

**Comment by nitrosx** [comment]
This should be addressed in the latest release.
