### ISSUE TITLE
Jobs migration: configuration

### ISSUE THREAD

**Issue by ddijken** [SciCatProject/backend#841]
Provide some examples of the configuration
Add JobsConfiguration in the scicat configuration
How to define and load them?

**Comment by sbliven** [comment]
[Draft schema](https://gist.github.com/sbliven/c1ec0783e0ab1975a34c4806f6ea48b3) from the workshop (yamale syntax; needs to be converted)

**Comment by sbliven** [comment]
Latest PR: #1021

**Comment by sbliven** [comment]
Configuration examples should be included here, but the majority of the documentation should probably be under issue https://github.com/SciCatProject/documentation/issues/53. Maybe we can close this as done, with the understanding that future PRs changing actions should also update the example configurations?

**Comment by despadam** [comment]
The configuration file is now well defined regarding the structure it should follow, and gets validated after reading the file. Currently is a json file but will soon be a yaml, as seen here: https://github.com/SciCatProject/scicat-backend-next/issues/1154
