### ISSUE TITLE
add support for arrays in scientificMetadata

### ISSUE THREAD

**Issue by jkotan** [SciCatProject/backend#924]
### Summary

At DESY we often store some parts of scientificMetadata in arrays/lists e.g. vectors
```
"vector": {
    "value": [1,1,0],
    "unit": "mm"
}
```
However, I such case the current algorithm to convert value and units to SI crashes.

### Expected Behaviour

I would like to support also  arrays/lists in  scientificMetadata as well.

**Comment by nitrosx** [comment]
@jkotan thank you so much for the PR.
Interesting enough, one of our instrument scientist just mention this exact feature.
I will review the PR soon.

**Comment by sbliven** [comment]
Isn't this a bug in the frontend display of arrays? I think we have arrays in some of our datasets, but we just display scientificMetadata as a JSON object without any restrictions or parsing.

**Comment by nitrosx** [comment]
Opened issue https://github.com/SciCatProject/scicat-backend-next/issues/984 with a proposed comprehensive solution that integrates the one proposed in this issue.
