### ISSUE TITLE
[idea] Handling of scan vars in scientific metadata

### ISSUE THREAD

**Issue by bpedersen2** [SciCatProject/backend#940]
The problem: 
If a variable is scanned in a  dataset, it's value can not be represented with a single value.
If you want to search for datasets, you expect to find it if the scan range did include it.

Way to a solution:
followup on #924 and if a value is an array, then  interpret it in the search as min/max.

(pseudo-code) Example search for T  = 100
```
search ( T =100 or 
           if T is array then 
                if T[0] < 100 and T[1]> 100
)
````

**Comment by nitrosx** [comment]
I am planning to discuss this topic at the next meeting.
I think we should define all the operators for the arrays, so than the behavior is clear.

**Comment by nitrosx** [comment]
Opened issue #984 with a proposed comprehensive solution that integrates the one proposed in this issue.
