### ISSUE TITLE
OpenAPI Schema

### ISSUE THREAD

**Issue by ChuckMoe** [SciCatProject/backend#941]
### Summary
Currenlty the OpenAPI schemas are not working as intended. The required parameters in the schema do not match the required parameters for the API and some are even opposite to each other.

### Steps to Reproduce
I created a python client from the OpenAPI schema json file from my local SciCat instance. Generating, installing and using it works just fine. When creating the `CreateRawDatasetDto` object in the client, I have to add the parameter `owner` because it is set as `required` in the OpenAPI schema. Doing this results in an `Error: Bad Request - whitelistValidation` response from the API though.

### Suggestion
Invert the class inheritance:
UpdatingClassDto as smallest subset of parameters
CreatingClassDto inherits from UpdatingClassDto
GettingClassDto (or only ClassDto) inherits from CreatingClassDto

This way you build up your parameter space and only show the parameters one is allowed to use in an API call. You can find a small practical example of this in Python [here](https://github.com/awtkns/fastapi-crudrouter/issues/109#issuecomment-1107664425)

### Notes
I can work on this issue.

**Comment by nitrosx** [comment]
@ChuckMoe thank you for your offer to work on the issue. We do appreciate.
Please go ahead and submit a PR when you are ready for us to review.
If you could include API tests (both positives and negative) for the issues that you reported, it would be awesome.

Please let me know if you have any question or need help, we will do our best to support your effort

**Comment by ChuckMoe** [comment]
Do you mean to test the API or the API specification (OpenAPI schema)? The API looks fine to me and I don't want to change that. It's basically it's documentation I want to change.

At the moment, there are two ways to test the API specifications that I can think of. One is to generate the client, then install and test if it works against the SciCat API. The other one is to save the OpenAPI specification as json file, parse it and check for inconsistencies manually. Both do have their pros and cons.

**Comment by nitrosx** [comment]
Apologies for not being clear, I meant add tests to test for the issue that you just found under the folder `tests` that you find in code.
That's where what we call the "API test" are stored and can be run by `npm run test:api:mocha`

**Comment by ChuckMoe** [comment]
I just opened a PR that shows how it can be done. For the example I choose the Instrument and Sample classes. This can be adapted for all classes.

## Instrument
### Create
The body for creating an Instrument is still the same
```
{
  "uniqueName": "string",
  "name": "string",
  "customMetadata": {}
}
```

### Update
But the allowed bodies for updating now look different.

#### Old
```
{
  "uniqueName": "string",
  "name": "string",
  "customMetadata": {}
}
```

#### New
```
{
  "name": "string",
  "customMetadata": {}
}
```

**Comment by nitrosx** [comment]
The project aims to have the the OpenAPI definition aligned to the data object. WE have put in a lot effort to find inconsistencies and fix them. We should have fix all of them, but we cannot guarantee that there are no more errors.

I close this issue with the understanding that new ones will be open when new inconsistencies are found.
