### ISSUE TITLE
RemoveUserIdentity in UsersService

### ISSUE THREAD

**Issue by ChuckMoe** [SciCatProject/backend#942]
### Summary
The return type of [users.service - removeUserIdentity](https://github.com/SciCatProject/scicat-backend-next/blob/b267738f12b2ffaaa84a4000b14d919caf2238cb/src/users/users.service.ts#L239) does not match the definition.

**Comment by nitrosx** [comment]
@ChuckMoe could you please create a PR to the official master branch? Thanks

**Comment by ChuckMoe** [comment]
Fixing the return type now gives me two errors during testing that I am currently trying to fix.
```
Access groups test › Make a request with user that has no accessGroups in his profile should succeed
    MongoServerError: Command find requires authentication
---
Access groups test › Make a request with user that has an Array as accessGroups in his profile should succeed
    MongoServerError: Command find requires authentication
```

**Comment by ChuckMoe** [comment]
I am sorry for the confusion. Seems I got this error due to a mismatch in my local dev environment.
