### ISSUE TITLE
Functional Accounts Minimal

### ISSUE THREAD

**Issue by ChuckMoe** [SciCatProject/backend#943]
### Summary
Currently, the default functionalAccount file is not used by default.

### Current Behaviour
Does not copy ```functionalAccounts.json.minimal.example``` into the container.

### Expected Behaviour
Copies ```functionalAccounts.json.minimal.example``` to ```functionalAccounts.json``` in the container.
Is the default functionality also wanted in the local dev environment? Additional steps would need to be taken then.

**Comment by nitrosx** [comment]
@ChuckMoe The current behavior is the intended one as I would like to force site administrators to create their own and define their own passwords. 
I would like to avoid that many different sites use the same functional accounts file.

**Comment by ChuckMoe** [comment]
@nitrosx That makes sense. I only got confused because it is still written in the README.
Thanks for clarifying.

**Comment by nitrosx** [comment]
Thank you so much for asking. We should fix the README.
Would you like to contribute with a PR?

**Comment by ChuckMoe** [comment]
Gladly

**Comment by nitrosx** [comment]
Thank you, Sir. I/We do appreciate

**Comment by nitrosx** [comment]
Relative PR has been merged.
