### ISSUE TITLE
[Idea] OpenAPI Generation

### ISSUE THREAD

**Issue by ChuckMoe** [SciCatProject/backend#958]
The OpenAPI definition allows to automatically generate clients for different languages. We could publish them with every release. On top of that, we can use these generated clients to test if the OpenAPI definition matches the internal implementation.

## Steps 
1. [x] Save the OpenAPI definition as a json file
2. [x] Generate clients with the just generated json file
3. [x] Write tests for at least one generated client and run them against the scicat-backend
4. [x] Publish the generated clients

## Questions
- Save json file with every startup or only when, for example, an environment variable is set?
- Which clients should we generate?
- Which language to choose for the tests? Typescript, Python, ...?

## References
- [OpenAPI Generator Action](https://github.com/openapi-generators/openapitools-generator-action)

**Comment by nitrosx** [comment]
SDK are generate automatically. The OpenAPI json file is retrieved directly from an instance of the related version of the BE.
SDK(s) are provided as is and tests is out of the scope of autogeneration. Testing is left to users.

Closing the issue as SDK are generated and published at every release.
