### ISSUE TITLE
Returned User DTO

### ISSUE THREAD

**Issue by ChuckMoe** [SciCatProject/backend#998]
### Summary
ReturnedUserDto requires `emailVerified` and `realm` but on a local auth, it does not send back this information.
This blocks auto generated clients.

### Steps to Reproduce
Start Scicat (only functionalAccounts added), use the local auth via the API.

SciCat Revision: ab011868f0d304ac17208b35e4d58ef4afe07bee

### Current Behaviour
It does not send `emailVerified` and `realm`.

### Expected Behaviour
It sends the two parameters in the response

**Comment by nitrosx** [comment]
@ChuckMoe thank you for doing all this testing.
When I created this DTO, I did not have auto generated clients on my radar. I simply excluded the fields that I thought were superfluous. 

Can you explain a little better why you would need those two fields to auto-generate successfully sdk/clients? 
...and more important, would you be able to create a PR for it?

Once I understand better (Slow monday brain), I will be happy to accept the PR.

**Comment by ChuckMoe** [comment]
@nitrosx The problem is simply that they are defined as required but are not necessarily send by the server. Because the documentation says they are required, the generated client throws an error, if they are not included in the response.
So there are two options now. Making these parameters optional (documentation) or sending them in the response every time. This solely depends on how you want to do this.

**Comment by nitrosx** [comment]
I would make them optional, but I will be happy with either options. I trust you pick the best solution..

**Comment by ChuckMoe** [comment]
As they are also optional in the User object, I opened a PR to set them as optional in the DTO as well.
